#!/usr/bin/env bash
# Hook PreToolUse (Bash matcher) — blocks git push if build/tests fail
# Only triggers on "git push" commands.
# Generated by forge-init.sh

INPUT=$(cat)

COMMAND=$(echo "$INPUT" | python3 -c "
import json, sys
data = json.load(sys.stdin)
inp = data.get('tool_input', {})
print(inp.get('command') or '')
" 2>/dev/null)

if ! echo "$COMMAND" | grep -qE '^git push'; then
  exit 0
fi

# Polyrepo guard — refuse to run from the workspace root or any non-git CWD.
# Agents MUST cd into the task's repo (declared by **Repo:** in the task file)
# before invoking git push.
if ! git rev-parse --show-toplevel >/dev/null 2>&1; then
  echo "BLOCKED: not inside a git repo (CWD=$(pwd))."
  echo "This workspace is a polyrepo. Each task declares **Repo:** — cd into that"
  echo "path before running git/build/test commands. The workspace root itself is"
  echo "NOT a git repo and never accepts pushes."
  exit 2
fi

REPO_ROOT=$(git rev-parse --show-toplevel)

# Excluded repos — handled manually by the human, never enforced by the forge.
# Normalize to forward slashes to handle Windows paths uniformly.
REPO_ROOT_NORM=$(echo "$REPO_ROOT" | tr '\\' '/')
case "$REPO_ROOT_NORM" in
  */Client/Angular|*/Client/Angular/*)
    echo "Pre-push: repo $REPO_ROOT is excluded from forge enforcement (manual handling). Push allowed."
    exit 0
    ;;
esac

echo "Pre-push verification in $REPO_ROOT"

# Build from the repo root. Each repo's solution/project is auto-discovered by
# dotnet build when run at its root; npm projects are detected via package.json.
if ls "$REPO_ROOT"/*.sln >/dev/null 2>&1 || ls "$REPO_ROOT"/**/*.csproj >/dev/null 2>&1; then
  (cd "$REPO_ROOT" && dotnet build) || { echo "BLOCKED: dotnet build failed in $REPO_ROOT"; exit 2; }
elif [ -f "$REPO_ROOT/package.json" ]; then
  (cd "$REPO_ROOT" && npm run build) || { echo "BLOCKED: npm run build failed in $REPO_ROOT"; exit 2; }
else
  echo "WARN: no .sln/.csproj/package.json detected at $REPO_ROOT — skipping build"
fi

echo "All checks passed. Push allowed."
exit 0
